version: "3.8"

# define frontend, backend, and database services
services:
  web:
    build: ./frontend
    image: vidly_web:1
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
  # web-tests:
  #   image: docker-compose-web
  #   volumes:
  #     - ./frontend:/app
  #   command: npm test
  api:
    build: ./backend
    image: vidly_api:1
    ports:
      - 3001:3001
    environment:
      # - DB_URL=mongodb://db/vidly
      DB_URL: mongodb://db/vidly
    volumes:
      - ./backend:/app
    # approach1:
    # override the npm start command in ./backend/Dockerfile
    # but we need to wait for the db container is up, so need to use a waiting script
    # command: ./wait-for db:27017 && migrate-mongo up && npm start

    # approach2: to use a docker-entrypoint.sh file to wait for mongoDB start
    command: ./docker-entrypoint.sh
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

  # api-tests:
  #   image: docker-compose-api
  #   depends_on: 
  #     - db
  #   volumes:
  #     - ./backend:/app
  #   command: npm test

# define a volume, please note the syntax
volumes:
  vidly: